services:
    bbdd:
        image: postgres
        container_name: postgres_db
        restart: always
        environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
        ports:
          - ${POSTGRES_PORT}:5432
        volumes:
          - postgres-db-volume:/var/lib/postgresql/data
          - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
          interval: 10s
          retries: 5
          start_period: 30s
          timeout: 10s
        networks:
            - db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - ${PGADMIN_PORT}:80
        volumes:
            - ./scripts/servers.json:/pgadmin4/servers.json
        networks:
            - db-network
        depends_on:
            - bbdd
            
    movies-backend:
        build:
            context: https://github.com/AgueroSalcinesIgnacio/cinema-backend-movies.git#develop
            dockerfile: Dockerfile
        image: movies-backend
        environment:
            DB_URL: ${POSTGRES_URL}
            PG_USER: ${POSTGRES_USER}
            PG_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${BACKEND_MOVIES_PORT}:8080
        
        depends_on:
            bbdd:
                condition: service_healthy
                restart: true
        networks:
            - db-network
            - backend-network
    
    users-backend:
        build:
            context: https://github.com/AgueroSalcinesIgnacio/cinema-backend-users.git#develop
            dockerfile: Dockerfile
        image: users-backend
        environment:
            DB_URL: ${POSTGRES_URL}
            PG_USER: ${POSTGRES_USER}
            PG_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${BACKEND_USERS_PORT}:8080
        
        depends_on:
            bbdd:
                condition: service_healthy
                restart: true
        networks:
            - db-network
            - backend-network
     
    api:
        image: devopsfaith/krakend
        ports:
          - "${API_GATEWAY_PORT}:8080"
        volumes:
          - ./scripts/krakend.json:/etc/krakend/krakend.json
        networks:
            - backend-network
            - api-network
        depends_on:
            - users-backend
            - movies-backend
        
    cinema-bff:
        build:
           context: https://github.com/AgueroSalcinesIgnacio/cinema-bff.git#feature/security
           dockerfile: Dockerfile
        image: cinema-bff
        environment:
            PORT: ${BFF_PORT}
            BACKEND_URL: ${API_GATEWAY_URL}
            ALLOW_ORIGINS: ${BFF_ALLOW_ORIGINS}
            BCRYPT_SALT: ${BFF_BCRYPT_SALT}
            JWT_SECRET: ${BFF_JWT_SECRET}
        volumes:
           - node_modules:/app/node_modules
        ports:
           - ${BFF_PORT}:3000
        depends_on:
            - api
        networks:
            - api-network
            - frontend-network
    cinema-frontend:
        build:
           context: https://github.com/AgueroSalcinesIgnacio/cinema-frontend.git#develop
           dockerfile: Dockerfile
        image: cinema-frontend
        environment:
            VITE_BASE_URL: ${BFF_BASE_URL}
        volumes:
           - node_modules:/app/node_modules
        ports:
           - ${FRONTEND_PORT}:9000
        depends_on:
            - cinema-bff
        networks:
            - frontend-network
            
volumes:
    node_modules:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./postgres/data
networks:
    db-network:
    backend-network:
    api-network:
    frontend-network:
